name: Deploy Web

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Upload files to server
        shell : bash
        env:
          HOST: 65.109.113.90
          USER: root
          TARGET: /var/www/html/www.rewahr.com
        run: |
          scp -r images $USER@$HOST:$TARGET
          scp -r css $USER@$HOST:$TARGET
          scp *.html $USER@$HOST:$TARGET
          scp -r components $USER@$HOST:$TARGET
